### ISSUE TITLE
 Could not pass event CreatureSpawnEvent to MoreBosses

### ISSUE THREAD

**Issue by hashashin** [Derpy00001/MoreBosses#1] opened 2019-10-16 11:59 UTC
Hi, getting this from time to time, I already removed one plugin that limits the phantoms, but the error persist but less frequent.

https://pastebin.com/NmG6Zsqj

Thanks.

**Comment by Derpy00001** [comment] 2019-10-17 03:04
This can be caused by not updating the configuration file (config.yml) to the most current version as health scales changed in r.2.3.2, because you're using the old config, the plugin is trying to read what should be the newest config resulting in values being absent causing the value to be 0, the outputs the error as the plugin using the value as a multiplier (phantom_health=phantom_health*multiplier) which outputs there error as value*0 = 0 and mobs health values cannot be 0.
You can update the config file by just deleting the MoreBosses/config.yml file and running the server again
[Image of file](https://i.gyazo.com/52ac11e7eaeaff31476b96e0c63b5812.png)

_If this issue still occurs, please feel free to contact me further_

**Comment by hashashin** [comment] 2019-10-17 13:14
As I already stated in discord, it keeps happening after a config regen. I double checked my plugins and should be nothing interfering with phantoms natural spawns.

Thanks.

**Comment by Derpy00001** [comment] 2019-10-21 19:40
I've figured out the issue causing this,
There was an issue with the code, as I the code was to grab a value "heath_scale.tier1.phantom" when the correct value name is "health_scale.tier0.phantom".
This will be released with the next version.
Sorry about any issues this has caused.

**Closed as completed by Derpy00001** 2019-10-21 19:40 UTC
Labels: bug, IllegalArgumentException Error
